-- MySQL Script generated by MySQL Workbench
-- 10/10/17 20:48:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PousoAlegril_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PousoAlegril_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PousoAlegril_BD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PousoAlegril_BD` ;

-- -----------------------------------------------------
-- Table `PousoAlegril_BD`.`Financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PousoAlegril_BD`.`Financeiro` (
  `idFinanceiro` INT NOT NULL COMMENT '',
  `data` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idFinanceiro`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PousoAlegril_BD`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PousoAlegril_BD`.`Mesa` (
  `idMesa` INT NOT NULL COMMENT '',
  `numero` INT NULL COMMENT '',
  `conta` FLOAT NULL DEFAULT NULL COMMENT '',
  `finalizada` TINYINT(1) NULL COMMENT '',
  `Financeiro_idFinanceiro` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idMesa`)  COMMENT '',
  INDEX `fk_Mesa_Financeiro1_idx` (`Financeiro_idFinanceiro` ASC)  COMMENT '',
  CONSTRAINT `fk_Mesa_Financeiro1`
    FOREIGN KEY (`Financeiro_idFinanceiro`)
    REFERENCES `PousoAlegril_BD`.`Financeiro` (`idFinanceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PousoAlegril_BD`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PousoAlegril_BD`.`Bebida` (
  `id` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `descricao` VARCHAR(45) NOT NULL COMMENT '',
  `categoria` INT NOT NULL COMMENT '',
  `disponivel` TINYINT(1) NOT NULL COMMENT '',
  `preco` FLOAT NOT NULL COMMENT '',
  `quantidade` FLOAT NOT NULL COMMENT '',
  `unidade` INT NULL COMMENT '',
  `servida` TINYINT(1) NULL COMMENT '',
  `numeroMesa` INT NULL COMMENT '',
  `Mesa_idMesa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Bebida_Mesa1_idx` (`Mesa_idMesa` ASC)  COMMENT '',
  CONSTRAINT `fk_Bebida_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `PousoAlegril_BD`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PousoAlegril_BD`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PousoAlegril_BD`.`Comida` (
  `id` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  `categoria` INT NULL COMMENT '',
  `disponivel` TINYINT(1) NULL COMMENT '',
  `preco` FLOAT NULL COMMENT '',
  `quantidade` FLOAT NULL COMMENT '',
  `unidade` INT NULL COMMENT '',
  `servida` TINYINT(1) NULL COMMENT '',
  `numMesa` INT NULL COMMENT '',
  `Mesa_idMesa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Comida_Mesa_idx` (`Mesa_idMesa` ASC)  COMMENT '',
  CONSTRAINT `fk_Comida_Mesa`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `PousoAlegril_BD`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PousoAlegril_BD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PousoAlegril_BD`.`Usuario` (
  `idUsuario` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `senha` VARCHAR(45) NULL COMMENT '',
  `funcao` INT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
